Added contributions and bug reporting sections to README
lotuslocke/open-pond pull request #3
Opened 2020-10-20 23:28 UTC by greer184

Add two sections to the README to facilitate issue reporting and feature development external to the Lotus Locke team. If anything makes sense to add to the descriptions (or my English is subpar), make notes of it and I'll update the PR.

2020-10-21 02:03 UTC, portends requested changes
small wording correction

2020-10-21 02:03 UTC, portends commented on README.md
> +what to look for in review. Make sure the code is clean and free of extraneous comments or notes.
```suggestion
what to look for in a review. Make sure the code is clean and free of extraneous comments or notes.
```

2020-10-21 22:54 UTC, greer184 commented on README.md
> +what to look for in review. Make sure the code is clean and free of extraneous comments or notes.
used "the" instead of "a" as it sounds a little better.

2020-10-22 01:52 UTC, portends approved these changes
Looks good to go :+1:

2020-10-22 22:00 UTC, merged

2020-10-25 16:07 UTC, nhanby46 commented
Great work :)